<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Evaluation Date</name>
   <tag></tag>
   <elementGuidId>52b7889b-6386-46cd-a4bd-93673f50b2fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uxTxtEvaluationDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uxTxtEvaluationDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8f3db2c-99a9-42dd-8dc6-22fcc6e540aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-valid ng-isolate-scope ng-not-empty ng-valid-date</value>
      <webElementGuid>066f17f4-2e23-433c-82e2-66320f773a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>uib-datepicker-popup</name>
      <type>Main</type>
      <value>MM/dd/yyyy</value>
      <webElementGuid>cb704c66-1f6b-4cc5-a024-32757ccc060b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>uib-datepicker-options</name>
      <type>Main</type>
      <value>dateOptions</value>
      <webElementGuid>06131510-a473-4009-9cfa-4353dae5025e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>is-open</name>
      <type>Main</type>
      <value>opened</value>
      <webElementGuid>25cf446f-9a55-4142-a9b3-b6a3bb42c082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>close-text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>e3f218bc-1cdd-48c2-ac0a-a9c686c4d70a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>mm/dd/yyyy</value>
      <webElementGuid>d3bd2aab-394a-44bb-9104-53a8a72fd392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>ngModel</value>
      <webElementGuid>c8cfac2e-7de2-4b79-a478-41af11d06358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min-date</name>
      <type>Main</type>
      <value>minDate</value>
      <webElementGuid>7527e4e0-5b91-4438-84fe-29f46c52d20a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-date</name>
      <type>Main</type>
      <value>maxDate</value>
      <webElementGuid>3477f547-9a72-4413-9213-b4e45e094c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>704cc248-4399-4d22-882d-fa3c96c8f6ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uxTxtEvaluationDate</value>
      <webElementGuid>0b592e55-1973-4b75-b3db-ff0d69375cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uxTxtEvaluationDate&quot;)</value>
      <webElementGuid>97276b08-68c6-441f-ab4b-fefccac20fe1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uxTxtEvaluationDate']</value>
      <webElementGuid>90852c2a-32c8-4a07-bbfe-461deb543ee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-content']/div/div[3]/div/div/form/div/div/div/ewn-datepicker/div/input</value>
      <webElementGuid>df9e2577-3a98-47d7-805e-361d032caab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ewn-datepicker/div/input</value>
      <webElementGuid>6f20b213-86e9-44b6-977b-2d3dfcc19fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'mm/dd/yyyy' and @id = 'uxTxtEvaluationDate']</value>
      <webElementGuid>d46a9186-d24b-4571-8e05-962ab35cf5ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
