<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DatePicker</name>
   <tag></tag>
   <elementGuidId>d11abd37-138f-46ef-8e6c-ec18e4bb2c68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//span[@class='ri-calendar-event-line'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ri-calendar-event-line</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>db05e46e-d119-4204-a591-0e474946cf81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ri-calendar-event-line</value>
      <webElementGuid>4022c4bc-2e1f-4f9a-8c5c-845275d63f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout-content&quot;)/div[@class=&quot;product-section ng-scope&quot;]/div[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane ng-scope active&quot;]/form[@class=&quot;form-horizontal ng-scope ng-invalid ng-invalid-required ng-valid-date ng-dirty ng-valid-parse&quot;]/div[@class=&quot;well well-sm ng-pristine ng-invalid ng-invalid-required ng-valid-date&quot;]/div[@class=&quot;row form-group form-group-sm&quot;]/div[@class=&quot;col-sm-9&quot;]/ewn-datepicker[@class=&quot;ng-pristine ng-untouched ng-valid ng-isolate-scope ng-not-empty ng-valid-required&quot;]/div[@class=&quot;ewn-datepicker input-group input-group-sm col-xs-12&quot;]/div[@class=&quot;input-group-btn&quot;]/button[@class=&quot;btn btn-primary&quot;]/span[@class=&quot;ri-calendar-event-line&quot;]</value>
      <webElementGuid>a4f84cf8-2d8a-4fb6-8bd5-f42eeba85fdb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-content']/div/div[3]/div/div/form/div/div/div/ewn-datepicker/div/div[2]/button/span</value>
      <webElementGuid>4ac6963e-0fa9-4882-89a0-f85f3090b0df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ewn-datepicker/div/div[2]/button/span</value>
      <webElementGuid>51169744-859f-407f-9760-4a5266ac868a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
