<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EvaluationAuthor</name>
   <tag></tag>
   <elementGuidId>fb98f59d-5df0-4409-a0fa-04cbb1663918</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='uxDdlEvaluationAuthor']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uxDdlEvaluationAuthor</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d4438046-4d9d-45fd-90d7-12074d9996a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uxDdlEvaluationAuthor</value>
      <webElementGuid>68bcf531-91c1-454c-b817-4cca1cbbbf8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uxDdlEvaluationAuthor</value>
      <webElementGuid>166e369d-d49e-4f67-8570-d3a13fa093b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-valid ng-not-empty</value>
      <webElementGuid>4b1b4048-50bd-43b4-b2c3-73225122abee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>filterCriteria.companyId</value>
      <webElementGuid>6636ed68-756f-40f3-8771-e23070cd9333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>evaluationAuthorChanged()</value>
      <webElementGuid>2d958ec3-5d56-4d8f-9d3a-c08f2feb2025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>f.id as f.name for f in filterData.operators | orderBy:'name'</value>
      <webElementGuid>a4fc0752-7ec6-4651-9000-094dade60f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Energy WorldnetKMS-The Automation TeamVijee Operator IncVijee The Fourth ReignVijee_The Third One</value>
      <webElementGuid>49443598-7827-4af8-9943-a96a992e4130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uxDdlEvaluationAuthor&quot;)</value>
      <webElementGuid>b68a94c5-821d-4599-891f-37864cebc5f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='uxDdlEvaluationAuthor']</value>
      <webElementGuid>c0660c18-2b26-42f6-9563-581b04059f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-content']/div/div[3]/div/div/form/ewn-evaluation-dual-listbox/div/div/div/select</value>
      <webElementGuid>d8b45104-8c24-4537-8c5a-7894009e9676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Evaluation Author:'])[1]/following::select[1]</value>
      <webElementGuid>68264698-3d1e-4518-a643-8377779e90b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User, MRA-010 - EWN-322805'])[1]/following::select[1]</value>
      <webElementGuid>8bdb0363-f09c-471a-9bfc-a261db3df4ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Evaluation Type:'])[1]/preceding::select[1]</value>
      <webElementGuid>1dd2aad0-9e53-4311-84bf-5143d126719e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order By:'])[1]/preceding::select[2]</value>
      <webElementGuid>3d6f5bbd-2630-4453-b3e6-503e4147e541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ewn-evaluation-dual-listbox/div/div/div/select</value>
      <webElementGuid>43e4efca-dfd1-4cf6-9b8f-d63b362c3db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'uxDdlEvaluationAuthor' and @id = 'uxDdlEvaluationAuthor' and (text() = ' Energy WorldnetKMS-The Automation TeamVijee Operator IncVijee The Fourth ReignVijee_The Third One' or . = ' Energy WorldnetKMS-The Automation TeamVijee Operator IncVijee The Fourth ReignVijee_The Third One')]</value>
      <webElementGuid>39918c66-c4f4-4818-90ec-3ec4515c89f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
