<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EvaluationType</name>
   <tag></tag>
   <elementGuidId>2a17b8e6-6a6e-4a05-a7c0-fe1872ac8997</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='uxDdlEvaluationType']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'uxDdlEvaluationType' and @id = 'uxDdlEvaluationType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uxDdlEvaluationType</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9b1ea24d-543b-4b20-8004-8f1225ed4af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uxDdlEvaluationType</value>
      <webElementGuid>c1ca3cc4-a52b-47ad-be5e-b747ca3933f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uxDdlEvaluationType</value>
      <webElementGuid>a495adc5-27ff-4218-a2e9-0d049d970f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-valid ng-not-empty</value>
      <webElementGuid>3c2fe80a-5f5c-49b8-aa95-fdb99eb3d901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>filterCriteria.evaluationTypeId</value>
      <webElementGuid>3591b0c7-c729-4ed5-b727-a04e793a0f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>f.id as f.name for f in filterData.evaluationTypes | orderBy:'name'</value>
      <webElementGuid>3cf20c96-649d-41b0-aa63-ed4b8cab4966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Computer Based TrainingInstructor-Led TrainingPerformance EvaluationRecord OnlyWritten Evaluation</value>
      <webElementGuid>94cff7f2-29cd-4f96-8d35-19598d6cbe24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uxDdlEvaluationType&quot;)</value>
      <webElementGuid>91041587-89da-4ca9-bc5b-ae47e5eaeac2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='uxDdlEvaluationType']</value>
      <webElementGuid>51fb346a-17e7-4db2-8667-f803e76f9e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-content']/div/div[3]/div/div/form/ewn-evaluation-dual-listbox/div/div[3]/div/select</value>
      <webElementGuid>0c22014f-e1af-43e6-beed-6099fb8f48b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Evaluation Type:'])[1]/following::select[1]</value>
      <webElementGuid>f69cc1a2-deb4-4342-9aea-b1f17119b2f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Evaluation Catalog:'])[1]/following::select[2]</value>
      <webElementGuid>78795f57-d675-4835-87c9-6cf3d80d48fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order By:'])[1]/preceding::select[1]</value>
      <webElementGuid>ea9fe804-3462-49e8-b29e-291df9d313cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter'])[2]/preceding::select[2]</value>
      <webElementGuid>cca9b831-55e4-457c-bf94-522ade3eb6f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>7597d60e-7223-4e15-add9-20ab3be965a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'uxDdlEvaluationType' and @id = 'uxDdlEvaluationType' and (text() = 'Computer Based TrainingInstructor-Led TrainingPerformance EvaluationRecord OnlyWritten Evaluation' or . = 'Computer Based TrainingInstructor-Led TrainingPerformance EvaluationRecord OnlyWritten Evaluation')]</value>
      <webElementGuid>e43bd46b-2461-4a32-991e-e5bc326f6e23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
