<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EvaluatorNhung, test (3rd Party)</name>
   <tag></tag>
   <elementGuidId>c7c8d24e-4f30-4a10-8550-468d3beb8b92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;uxDdlEvaluator&quot;]/option[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uxDdlEvaluator</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ceb572fb-da20-4842-afc1-a56e7734f71c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uxDdlEvaluator</value>
      <webElementGuid>673d1d16-db24-4abd-8fa2-83c425787986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uxDdlEvaluator</value>
      <webElementGuid>b84d60c8-b58d-4ddc-80c6-f38a6fcefd70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required</value>
      <webElementGuid>24c3f5ca-febe-4403-81bd-38b921639283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>criteria.evaluatorUserId</value>
      <webElementGuid>eab1ddd6-cadf-4bfc-bd2d-c5bb924968a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>f.id as (f.name + (f.isThirdParty ? ' (' + ('ui_SubmitEvaluations_Evaluator_3rdParty' | translate) + ')' : '')) for f in evaluators | orderBy:'name'</value>
      <webElementGuid>07b34a05-5075-48e3-8940-47b8cc5fc704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>!false &amp;&amp; isEvaluatorRequired()</value>
      <webElementGuid>6448385b-b9e8-4b9d-b126-df4a30642926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>ce8a4ee7-9238-43f9-9bb9-b448e1418b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select EvaluatorNhung, test (3rd Party)</value>
      <webElementGuid>8261a02b-59df-49e7-9291-03716e8f8552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uxDdlEvaluator&quot;)</value>
      <webElementGuid>c3ba104a-d94b-4530-8fed-779e135eb2dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='uxDdlEvaluator']</value>
      <webElementGuid>7eaf4d56-2383-49aa-ac6e-9f84c67dd37d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-content']/div/div[3]/div/div/form/div/div[3]/div/select</value>
      <webElementGuid>4bac77cf-b5c9-4ae4-9da5-1ca600deae4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Evaluator:'])[1]/following::select[1]</value>
      <webElementGuid>dafbcdc1-9bd0-4eb6-ba20-d97265c9e233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Training Status:'])[1]/following::select[2]</value>
      <webElementGuid>10497c61-119c-474a-af7e-4737b9c45ad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Required'])[1]/preceding::select[1]</value>
      <webElementGuid>9c9c0d8d-8a7a-4de8-88f7-03a2c99f17b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location:'])[1]/preceding::select[1]</value>
      <webElementGuid>6dfe43ec-e338-410d-a69f-59e83d0204bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[3]/div/select</value>
      <webElementGuid>8182f047-3f23-4312-8c9d-cf6ccae35220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'uxDdlEvaluator' and @id = 'uxDdlEvaluator' and (text() = 'Select EvaluatorNhung, test (3rd Party)' or . = 'Select EvaluatorNhung, test (3rd Party)')]</value>
      <webElementGuid>4cf2715e-ab6c-4936-8c1b-e76cb2b4bd1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
