<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SearchAvailableEvaluationField</name>
   <tag></tag>
   <elementGuidId>ce90a777-77e9-4ad4-8179-be0fef044def</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@placeholder=&quot;Search&quot;])[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@placeholder = 'Search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.input-group.input-group-sm > input.form-control.ng-pristine.ng-untouched.ng-valid.ng-empty</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af895167-8e7a-45d1-8053-a081f38d4bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>2a94b4eb-d02d-4abf-a80b-4284ca9e52c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>vm.left.search</value>
      <webElementGuid>913da273-66a6-40e8-a124-4aadcb4877f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keydown</name>
      <type>Main</type>
      <value>vm.preventSubmit($event)</value>
      <webElementGuid>9540937f-797b-46c7-a328-e8cc3fa8b3d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>7978c1fd-28cd-430e-86d3-bddb663f32d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout-content&quot;)/div[@class=&quot;product-section ng-scope&quot;]/div[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane ng-scope active&quot;]/form[@class=&quot;form-horizontal ng-pristine ng-scope ng-invalid ng-invalid-required ng-valid-date&quot;]/ewn-employee-dual-listbox[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;col-lg-10 col-lg-offset-1&quot;]/ewn-dual-list[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;dual-list clearfix&quot;]/div[@class=&quot;dual-list-left col-xs-12 col-sm-12 col-md-5 col-lg-5 droppable&quot;]/div[@class=&quot;input-group input-group-sm&quot;]/input[@class=&quot;form-control ng-pristine ng-untouched ng-valid ng-empty&quot;]</value>
      <webElementGuid>e1426b99-28dc-4c6a-b2f6-4d16de81f86e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-content']/div/div[3]/div/div/form/ewn-employee-dual-listbox/div/ewn-dual-list/div/div/div/input</value>
      <webElementGuid>4def7a77-4819-45c7-b791-3dd11a3ff513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ewn-dual-list/div/div/div/input</value>
      <webElementGuid>13629fe3-c321-4844-b9f6-e87a93c5a2d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search']</value>
      <webElementGuid>2c1f7178-b0ea-4ad0-83a7-cf6082a56907</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
