<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_MRA-010_Task (11)_ri-checkbox-circle-f_673c6c</name>
   <tag></tag>
   <elementGuidId>6f85a327-e8ca-4b7b-a494-a3a062ad917b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='user0']/task-requirement-list/table/tbody/tr/td[6]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ri-checkbox-circle-fill.ri-green.ng-scope</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ededb4bc-0b6f-40b9-9cc9-e336c648dbcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ri-checkbox-circle-fill ri-green ng-scope</value>
      <webElementGuid>1108e864-72e7-478a-a7a4-0627db1a15b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-switch-when</name>
      <type>Main</type>
      <value>Completed</value>
      <webElementGuid>73eb96e1-4f27-45c1-ab0d-dfb55fe8b3f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user0&quot;)/task-requirement-list[@class=&quot;ng-isolate-scope&quot;]/table[@class=&quot;table table-striped table-condensed task-requirement-list&quot;]/tbody[1]/tr[@class=&quot;task-row nested-table-accordion-header ng-scope&quot;]/td[@class=&quot;glyph-cell&quot;]/span[@class=&quot;ri-checkbox-circle-fill ri-green ng-scope&quot;]</value>
      <webElementGuid>1e75c445-24c0-4e9c-b02b-5d391b73c468</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='user0']/task-requirement-list/table/tbody/tr/td[6]/span</value>
      <webElementGuid>82e8ad8f-2c89-42d8-a390-4e693949d3eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/span</value>
      <webElementGuid>34cbd245-8a2c-41a8-8ee1-143fd7fe4bc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
