<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_January 2023</name>
   <tag></tag>
   <elementGuidId>bafd6504-a160-411a-882c-9efccc572889</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='datepicker-891-9751-title']/strong</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>strong.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>36f8ef73-68e9-4fe2-91e6-5659de7a4bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>3d521049-dda2-4abf-9323-2ffd17f27f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>January 2023</value>
      <webElementGuid>245d232a-e81a-4d6d-8180-83065cb08d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datepicker-891-9751-title&quot;)/strong[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>59092955-7c5a-43c4-b0cf-b18ca48f0468</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='datepicker-891-9751-title']/strong</value>
      <webElementGuid>8817a50d-9bff-4a59-8699-17535a71ca9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Evaluation Date:'])[1]/following::strong[1]</value>
      <webElementGuid>1332c12f-af82-4f8f-8a89-8e6fc5590c00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected Evaluations'])[1]/following::strong[1]</value>
      <webElementGuid>61a74a0a-3505-4415-a36a-f4722b256a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sun'])[1]/preceding::strong[1]</value>
      <webElementGuid>0b7fb963-cd07-4f92-b6eb-16cc40f84f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mon'])[1]/preceding::strong[1]</value>
      <webElementGuid>06e6a4da-e9f6-4a3a-9a9c-8f9d7b532b61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='January 2023']/parent::*</value>
      <webElementGuid>4d93a1f9-de1d-4e03-b9da-b8baffb8fbe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/strong</value>
      <webElementGuid>052131b6-2ac2-4e89-b39c-5a8a21b07adf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'January 2023' or . = 'January 2023')]</value>
      <webElementGuid>53b107d3-b465-470d-85b5-67539bcdd432</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
