<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Training Status _914866</name>
   <tag></tag>
   <elementGuidId>6f742325-d81b-403d-a3c9-aeb9be0ac1ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='uxDdlTrainingStatus']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uxDdlTrainingStatus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f52c88a7-207e-4b50-9ed2-086a796eb31c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uxDdlTrainingStatus</value>
      <webElementGuid>2aabd2c1-d837-4ae8-80e0-ef2bff9f7644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uxDdlTrainingStatus</value>
      <webElementGuid>b365f4f8-4e37-44fc-95b7-813bb1aac4f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required</value>
      <webElementGuid>43ce5189-975b-4edf-a8e5-9addaf1fe79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>criteria.status</value>
      <webElementGuid>02840c34-85b4-42ed-af0f-2817c4bb642d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>criteria.isPassed = (criteria.status == 'Passed')</value>
      <webElementGuid>5b9177bd-f7a8-4e6a-9ff6-7006b8ddc5f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>!false</value>
      <webElementGuid>d8d34979-fb85-4dcf-b607-832c58980dc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>ac9df3ac-0f45-4a07-a4fb-7fdcfc99f776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Select Training Status
                    Passed
                    Failed
                </value>
      <webElementGuid>c47fe5be-191d-4816-9ab5-aaf59d950609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uxDdlTrainingStatus&quot;)</value>
      <webElementGuid>3bdfff15-6f64-4b80-a95e-6cc07c33509f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='uxDdlTrainingStatus']</value>
      <webElementGuid>02673df0-c1fd-43af-866c-b2c282d0cacd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-content']/div/div[3]/div/div/form/div/div[2]/div/select</value>
      <webElementGuid>4552bf0a-e308-4e1b-83c7-f0fe2d8daf4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Training Status:'])[1]/following::select[1]</value>
      <webElementGuid>2d879275-1e39-4d9d-9955-12d0af9f1bfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Evaluation Date:'])[1]/following::select[1]</value>
      <webElementGuid>5523b4b8-cfed-4608-acfd-8b49375243d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Required'])[1]/preceding::select[1]</value>
      <webElementGuid>83a0c136-e62f-4b8f-86c7-6150f6affd55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Evaluator:'])[1]/preceding::select[1]</value>
      <webElementGuid>5fb569d5-330d-44ac-976e-0dbd9ffb17e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/select</value>
      <webElementGuid>a4fbb660-2e9f-45bd-b079-4903d33c5596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'uxDdlTrainingStatus' and @id = 'uxDdlTrainingStatus' and (text() = '
                    Select Training Status
                    Passed
                    Failed
                ' or . = '
                    Select Training Status
                    Passed
                    Failed
                ')]</value>
      <webElementGuid>359b26e9-8d8a-470f-9020-4580ce208d9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
