<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Organizational Tool Status</name>
   <tag></tag>
   <elementGuidId>157bf4f8-cae0-4706-83db-3cce762cc484</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='View user status by organizational tool'])[2]/preceding::div[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Organizational Tool Status' or . = 'Organizational Tool Status')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9aec248e-7a63-4561-ad2d-fce70bbf840c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link-title ng-binding</value>
      <webElementGuid>f963bde7-bf0b-4aa1-b352-9598cdb3a30d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind</name>
      <type>Main</type>
      <value>link.title</value>
      <webElementGuid>29b56caa-29a5-42c7-9371-45a8bf0cbe88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Organizational Tool Status</value>
      <webElementGuid>b7c69528-1b40-4b98-92d1-278449a0c45c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordiongroup-105-5482-panel&quot;)/div[@class=&quot;panel-body&quot;]/ul[@class=&quot;list-group ng-scope&quot;]/li[@class=&quot;list-group-item side-menu-list ng-scope&quot;]/div[@class=&quot;side-menu-list-container&quot;]/a[1]/div[@class=&quot;submenu-item&quot;]/div[@class=&quot;link-title ng-binding&quot;]</value>
      <webElementGuid>3d82490e-a329-43f8-aa01-96e180b9b50d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordiongroup-105-5482-panel']/div/ul/li[2]/div/a/div/div</value>
      <webElementGuid>05e2e182-9640-4d5d-81c8-7e15d30e7b9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View the task or evaluation status of users'])[1]/following::div[4]</value>
      <webElementGuid>9fc13b83-6bb0-4825-ace7-328dab597184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::div[5]</value>
      <webElementGuid>cae0928c-b7ec-4e7b-94d1-c83bf617039b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View user status by organizational tool'])[2]/preceding::div[1]</value>
      <webElementGuid>0e5f3d8d-f09a-47c7-a21b-d5c22c0db4c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity'])[2]/preceding::div[3]</value>
      <webElementGuid>e863ccd0-800f-42c9-888b-f18dc18a18b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div/ul/li[2]/div/a/div/div</value>
      <webElementGuid>3f42828c-9581-45e6-aeff-d6168692e2e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Organizational Tool Status' or . = 'Organizational Tool Status')]</value>
      <webElementGuid>62c14cb2-afd3-441f-ab73-c5e1fbe1d1b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordiongroup-113-3091-panel']/div/ul/li[2]/div/a/div/div</value>
      <webElementGuid>34f528f2-c0a6-4b2e-8e12-b7d8428b5830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/div/ul/li[2]/div/a/div/div</value>
      <webElementGuid>a9ab70ad-7b2a-407c-b3c7-8a99ab9f756a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
