<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filter_pull-right ng-pristine ng-unto_0c5e03</name>
   <tag></tag>
   <elementGuidId>8fbcae7d-d3c7-42ea-9daf-38b27a65a89a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-lg-10.col-lg-offset-1.ng-scope > ewn-dual-list.ng-isolate-scope > div.dual-list.clearfix > div.dual-list-left.col-xs-12.col-sm-12.col-md-5.col-lg-5.droppable > div.list-group > div.list-group-item.list-group-header.active > input.pull-right.ng-pristine.ng-untouched.ng-valid.ng-empty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[15]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a37a5e97-d538-48e0-a36f-c1bdf6fa7dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>acf4a350-1caf-42b6-8ba7-3cb818d36593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pull-right ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>004e4a07-9ca2-46f3-abb1-e5f36e29bb9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>vm.left.allSelected</value>
      <webElementGuid>001669a2-9d71-4e08-b4c3-95bbdf7237b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>vm.toggleAll(vm.left)</value>
      <webElementGuid>f4f6049c-0368-49c1-8f96-c907864e6c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordiongroup-439-8863-panel&quot;)/div[@class=&quot;panel-body&quot;]/div[@class=&quot;col-lg-10 col-lg-offset-1 ng-scope&quot;]/ewn-dual-list[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;dual-list clearfix&quot;]/div[@class=&quot;dual-list-left col-xs-12 col-sm-12 col-md-5 col-lg-5 droppable&quot;]/div[@class=&quot;list-group&quot;]/div[@class=&quot;list-group-item list-group-header active&quot;]/input[@class=&quot;pull-right ng-pristine ng-untouched ng-valid ng-empty&quot;]</value>
      <webElementGuid>48b458be-4806-4d32-b795-c809ee607607</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[15]</value>
      <webElementGuid>9596fb54-de5f-4b80-9159-809463c4cd74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordiongroup-439-8863-panel']/div/div[3]/ewn-dual-list/div/div/div[2]/div/input</value>
      <webElementGuid>88224949-14e0-43b9-a5df-a183d6065ea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ewn-dual-list/div/div/div[2]/div/input</value>
      <webElementGuid>b6740c40-6762-46dd-ae61-bf49b80050aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>f6f9611b-e861-43df-8f71-0514c84d3384</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
