<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_NTC (by Natallia) Natallia-Contracto_786096</name>
   <tag></tag>
   <elementGuidId>517a809a-0405-470c-ab6c-f766ed518771</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#companies</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='companies']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>74a11a7f-bf01-4eaa-a527-ce90109a2851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>companies</value>
      <webElementGuid>14ecf648-6e05-44fd-806d-e755ebc60455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>d29b48b7-1fbe-494c-8150-b5036997756e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>vm.associateCriteria.companyId</value>
      <webElementGuid>5763dade-b980-4d97-a6d3-b2eac45ee407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>vm.onCompanyChanged()</value>
      <webElementGuid>18f1ac29-9cc6-402e-8ffb-a6012f5822c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>c.id as c.name for c in vm.filters.companies</value>
      <webElementGuid>44b4f14c-fa28-400e-9ccf-1d6812892019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NTC (by Natallia) ©Natallia-Contractors LLCPropane &amp; Butane LLC DEMO (by Natallia) ©Quantum-Operator LLC (by Natallia) ©</value>
      <webElementGuid>93ca6bfa-4d04-42ee-9277-04eb41a85899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;companies&quot;)</value>
      <webElementGuid>fae924d3-2fe5-443b-9b05-d32ae6cc9ffe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='companies']</value>
      <webElementGuid>25d94cde-3dd0-41b8-99c4-197fb63948d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-content']/div/div/div/div/form/div/div/div/div/div/select</value>
      <webElementGuid>18b4617e-d1db-4931-8d47-a33253dc119b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Results for Employees of:'])[1]/following::select[1]</value>
      <webElementGuid>98965e26-ba6d-4b82-90ff-94a29130df76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View employee qualification status based on assigned organizational tools.'])[1]/following::select[1]</value>
      <webElementGuid>a655704e-c703-4fe3-8801-006feb2c4795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report View:'])[1]/preceding::select[1]</value>
      <webElementGuid>b7c0c152-98f6-4ce7-9a70-889b706afbc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available Org Tools'])[1]/preceding::select[2]</value>
      <webElementGuid>7f0335c6-4168-45e1-8a21-82f9773d9cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>bf402cea-2909-495b-80e6-bf45a4e0a939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'companies' and (text() = 'NTC (by Natallia) ©Natallia-Contractors LLCPropane &amp; Butane LLC DEMO (by Natallia) ©Quantum-Operator LLC (by Natallia) ©' or . = 'NTC (by Natallia) ©Natallia-Contractors LLCPropane &amp; Butane LLC DEMO (by Natallia) ©Quantum-Operator LLC (by Natallia) ©')]</value>
      <webElementGuid>670f9c7c-c1f8-475d-968f-de0989e24abb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
