<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pipeline Inspector ProgramBlack Hill_6c4e1c</name>
   <tag></tag>
   <elementGuidId>1a6221bc-af6c-41d8-83f3-4ede139a4e7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uxDdlTaskList</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='uxDdlTaskList']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ff413f5d-9272-4dde-bc62-c681af6a8bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>vmMain.taskListSelectionChanged()</value>
      <webElementGuid>37f4e274-b8ee-4f41-867b-b424571443fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uxDdlTaskList</value>
      <webElementGuid>f6d45084-fbae-49d3-87b7-9d25f4b7db92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uxDdlTaskList</value>
      <webElementGuid>2372b0c5-d8d9-454e-ba96-28219a440e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-valid ng-not-empty</value>
      <webElementGuid>e1f6956a-79c9-4189-ab1c-4926badce734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>vmMain.reportCriteria.taskListId</value>
      <webElementGuid>3311302f-0ad2-4e55-ab4f-84935cedd3c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>f.id as (f.name | translate) group by f.companyName for f in vmMain.taskLists | filter:vmMain.filterTaskLists | orderBy:['companyName', 'name']</value>
      <webElementGuid>5458c27f-fdbf-486c-bad7-df83ccaebace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pipeline Inspector ProgramBlack Hills Energy's B31Q Task List1472_Subscr-related1692_LIST1692_SCORM1787_CBTArchivedAthleticsAug-2022Automate_ItBoot CampEnergy WorldnetExpiring_SoonLCMS-86List_Summer-22May-2022NTC_01.2022NTC_Jan_4_OrgToolPAST_Deprecated_LISTShared_by_3CompSportsButane_EvalsCBT+PE=ListHide_ArchivedPrehistoric_May-2211/11_Test12.9.21_PE_List30_Qs4_Org_ToolArch_Bef2019Archived_Task_CondDec-2021Development-DEMO TaskEngine+BatteryJune-2022List -1849May-2022MediaNO_01.06.2022_ProdPEs+REs_LISTScore_Enforce-1SCORM-46SCORM_Task_ListTRAINING_ONLYWelding, etc.Wollam</value>
      <webElementGuid>0bb865eb-55d8-4e66-ad10-83907ad41752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uxDdlTaskList&quot;)</value>
      <webElementGuid>00657b55-3dd2-4d5e-bb51-3288348191c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='uxDdlTaskList']</value>
      <webElementGuid>b0eb8e31-b631-4782-8d1f-58176395f667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmTaskStatus']/div/div/div/div/div/select</value>
      <webElementGuid>183bc5aa-7586-4e70-9048-0c89da25b781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Task List:'])[1]/following::select[1]</value>
      <webElementGuid>f0ecb4e3-862a-4876-96af-4f576cc5ff12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Results'])[1]/following::select[1]</value>
      <webElementGuid>61634629-d9d1-4836-ae27-fbb1496d0462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report View:'])[1]/preceding::select[1]</value>
      <webElementGuid>1222e51b-2c28-41be-9a40-fad63816b040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Results for Employees of:'])[1]/preceding::select[2]</value>
      <webElementGuid>076e7027-79ce-453c-800b-f52297ebb950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>a061ced2-49ec-4c58-9851-2886d00b72b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'uxDdlTaskList' and @name = 'uxDdlTaskList' and (text() = concat(&quot;Pipeline Inspector ProgramBlack Hills Energy&quot; , &quot;'&quot; , &quot;s B31Q Task List1472_Subscr-related1692_LIST1692_SCORM1787_CBTArchivedAthleticsAug-2022Automate_ItBoot CampEnergy WorldnetExpiring_SoonLCMS-86List_Summer-22May-2022NTC_01.2022NTC_Jan_4_OrgToolPAST_Deprecated_LISTShared_by_3CompSportsButane_EvalsCBT+PE=ListHide_ArchivedPrehistoric_May-2211/11_Test12.9.21_PE_List30_Qs4_Org_ToolArch_Bef2019Archived_Task_CondDec-2021Development-DEMO TaskEngine+BatteryJune-2022List -1849May-2022MediaNO_01.06.2022_ProdPEs+REs_LISTScore_Enforce-1SCORM-46SCORM_Task_ListTRAINING_ONLYWelding, etc.Wollam&quot;) or . = concat(&quot;Pipeline Inspector ProgramBlack Hills Energy&quot; , &quot;'&quot; , &quot;s B31Q Task List1472_Subscr-related1692_LIST1692_SCORM1787_CBTArchivedAthleticsAug-2022Automate_ItBoot CampEnergy WorldnetExpiring_SoonLCMS-86List_Summer-22May-2022NTC_01.2022NTC_Jan_4_OrgToolPAST_Deprecated_LISTShared_by_3CompSportsButane_EvalsCBT+PE=ListHide_ArchivedPrehistoric_May-2211/11_Test12.9.21_PE_List30_Qs4_Org_ToolArch_Bef2019Archived_Task_CondDec-2021Development-DEMO TaskEngine+BatteryJune-2022List -1849May-2022MediaNO_01.06.2022_ProdPEs+REs_LISTScore_Enforce-1SCORM-46SCORM_Task_ListTRAINING_ONLYWelding, etc.Wollam&quot;))]</value>
      <webElementGuid>3766aba6-79f3-4b10-b290-18d6eaf0db27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
